AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Textract document processing application

Globals:
  Function:
    Timeout: 900  # Maximum timeout for Lambda (15 minutes)
    MemorySize: 1024
    Runtime: nodejs22.x
    Environment:
      Variables:
        COMPANY_FIELDS_TABLE: !Ref AMTCompanyFieldsTable

Resources:
  # Lambda Functions
  AMTTextractProcessorFunctionAdvanced:
    Type: AWS::Serverless::Function
    Properties:
      Handler: AMTTextractProcessorFunctionAdvanced.handler
      CodeUri: ./
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref AMTDocumentBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref AMTCompanyFieldsTable
        - Statement:
            - Effect: Allow
              Action:
                - textract:AnalyzeDocument
                - textract:StartDocumentAnalysis
                - textract:GetDocumentAnalysis
              Resource: '*'


  AMTTextractProcessorFunctionBasic:
    Type: AWS::Serverless::Function
    Properties:
      Handler: AMTTextractProcessorFunctionBasic.handler
      CodeUri: ./
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref AMTDocumentBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref AMTCompanyFieldsTable
        - Statement:
            - Effect: Allow
              Action:
                - textract:AnalyzeDocument
                - textract:StartDocumentAnalysis
                - textract:GetDocumentAnalysis
              Resource: '*'


  # S3 Bucket for document uploads
  AMTDocumentBucket:
    Type: AWS::S3::Bucket
    DependsOn: 
      - S3InvokePermission
      - S3InvokePermissionBasic
      - AMTDocumentBucketPolicy
    Properties:
      BucketName: !Sub 'amt-poc-documents'
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt AMTTextractProcessorFunctionAdvanced.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: advance/
          - Event: s3:ObjectCreated:*
            Function: !GetAtt AMTTextractProcessorFunctionBasic.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: basic/

  # DynamoDB Tables
  AMTCompanyFieldsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'amt-poc-company-fields'
      AttributeDefinitions:
        - AttributeName: company
          AttributeType: S
      KeySchema:
        - AttributeName: company
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # S3 Bucket Policy
  AMTDocumentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AMTDocumentBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: textract.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${AMTDocumentBucket}/*'

  # Lambda Permission for S3
  S3InvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref AMTTextractProcessorFunctionAdvanced
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${AMTDocumentBucket}'
      #add for basic function
  S3InvokePermissionBasic:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref AMTTextractProcessorFunctionBasic
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${AMTDocumentBucket}'



Outputs:
  AMTDocumentBucketName:
    Description: Name of the S3 bucket for document uploads
    Value: !Ref AMTDocumentBucket

  AMTCompanyFieldsTableName:
    Description: Name of the DynamoDB table for company configurations
    Value: !Ref AMTCompanyFieldsTable

  AMTTextractProcessorFunctionAdvanced:
    Description: Lambda function ARN
    Value: !GetAtt AMTTextractProcessorFunctionAdvanced.Arn

  AMTTextractProcessorFunctionBasic:
    Description: Lambda function ARN
    Value: !GetAtt AMTTextractProcessorFunctionBasic.Arn