AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for Textract document processing application

Globals:
  Function:
    Timeout: 900  # Maximum timeout for Lambda (15 minutes)
    MemorySize: 1024
    Runtime: nodejs22.x
    Environment:
      Variables:
        COMPANY_FIELDS_TABLE: !Ref AMTCompanyFieldsTable

Resources:

  # S3 Bucket for document uploads
  AMTDocumentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'amt-poc-documents'

  # Lambda Functions
  AMTTextractProcessorFunctionAdvanced:
    Type: AWS::Serverless::Function
    Properties:
      Handler: AMTTextractProcessorFunctionAdvanced.handler
      CodeUri: ./
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref AMTDocumentBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: advance/

  AMTTextractProcessorFunctionBasic:
    Type: AWS::Serverless::Function
    Properties:
      Handler: AMTTextractProcessorFunctionBasic.handler
      CodeUri: ./
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref AMTDocumentBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: basic/

  # DynamoDB Table
  AMTCompanyFieldsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'amt-poc-company-fields'
      AttributeDefinitions:
        - AttributeName: company
          AttributeType: S
      KeySchema:
        - AttributeName: company
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  #S3 Bucket Policy (Textract access only)
  AMTDocumentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AMTDocumentBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: textract.amazonaws.com
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource: !Sub 'arn:aws:s3:::${AMTDocumentBucket}/*'
  
  #roles for lambda functions to access S3 and DynamoDB and Textract
  AMTTextractProcessorFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AMTTextractProcessorFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub 'arn:aws:s3:::${AMTDocumentBucket}/*'
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt AMTCompanyFieldsTable.Arn
              - Effect: Allow
                Action:
                  - textract:AnalyzeDocument
                  - textract:StartDocumentAnalysis
                  - textract:GetDocumentAnalysis
                Resource:
                  - '*'

# Outputs:
  AMTDocumentBucketName:
    Description: Name of the S3 bucket for document uploads
    Value: !Ref AMTDocumentBucket

  AMTCompanyFieldsTableName:
    Description: Name of the DynamoDB table for company configurations
    Value: !Ref AMTCompanyFieldsTable

  AMTTextractProcessorFunctionAdvanced:
    Description: Lambda function ARN
    Value: !GetAtt AMTTextractProcessorFunctionAdvanced.Arn

  AMTTextractProcessorFunctionBasic:
    Description: Lambda function ARN
    Value: !GetAtt AMTTextractProcessorFunctionBasic.Arn

  AMTDocumentBucketPolicy:
    Description: S3 bucket policy for Textract access
    Value: !Ref AMTDocumentBucketPolicy

  AMTTextractProcessorFunctionRole:
    Description: IAM role for Textract processor functions
    Value: !GetAtt AMTTextractProcessorFunctionRole.Arn

  AMTTextractProcessorFunctionRoleName:
    Description: IAM role name for Textract processor functions
    Value: !Ref AMTTextractProcessorFunctionRole

  AMTTextractProcessorFunctionRolePolicy:
    Description: IAM role policy for Textract processor functions
    Value: !GetAtt AMTTextractProcessorFunctionRole.Policy.Arn
